<?php
require_once 'config.php';
$pageTitle = 'Fresh from our family farm';
$featured = [];
try { $featured = db()->query('SELECT * FROM products WHERE featured = 1 ORDER BY id DESC LIMIT 3')->fetchAll(); } catch (Throwable $e) { $featured = []; }
include 'includes/header.php';
?>
<section class="hero"><div class="container hero-content"><div class="eyebrow">Raised with care · delivered with pride</div><h1>Good mornings start with better eggs.</h1><p>Fresh farm eggs, healthy chicks and the trusted essentials to grow your own flock. From our family farm in Kiambu to your kitchen.</p><div class="hero-actions"><a class="btn btn-primary" href="shop.php">Shop the farm →</a><a class="btn btn-light" href="about.php">Meet our flock</a></div></div></section>
<section class="section"><div class="container"><div class="section-heading"><div><div class="eyebrow">What are you looking for?</div><h2>Pick your kind of fresh.</h2></div><a class="text-link" href="shop.php">View all products →</a></div><div class="categories"><a class="category-card" href="shop.php?category=Fresh+Eggs"><h3>Fresh eggs</h3><p>Collected at sunrise, delivered with care.</p></a><a class="category-card" href="shop.php?category=Day-old+Chicks"><h3>Healthy chicks</h3><p>A confident start for your next flock.</p></a><a class="category-card" href="shop.php?category=Feed"><h3>Farm essentials</h3><p>Everything your birds need to thrive.</p></a></div></div></section>
<section class="feature-band"><div class="container feature-grid"><div class="feature"><div class="feature-icon">◉</div><h3>Farm fresh</h3><p>Collected and packed daily.</p></div><div class="feature"><div class="feature-icon">✓</div><h3>Healthy by nature</h3><p>Responsible, careful raising.</p></div><div class="feature"><div class="feature-icon">⌁</div><h3>Delivered simply</h3><p>Reliable local delivery.</p></div><div class="feature"><div class="feature-icon">♡</div><h3>Here to help</h3><p>Real advice from our farm.</p></div></div></section>
<section class="section"><div class="container"><div class="section-heading"><div><div class="eyebrow">The farm stand</div><h2>Favourites this week.</h2></div><p>Small-batch picks that keep our customers coming back.</p></div><div class="product-grid"><?php foreach ($featured as $product): ?><article class="product-card"><div class="product-image <?= str_contains(strtolower($product['name']), 'chick') ? 'chicks' : 'eggs' ?>"><span class="badge">Farm favourite</span></div><div class="product-info"><div class="rating">★★★★★ <span>(<?= e((string)$product['rating']) ?>)</span></div><h3><?= e($product['name']) ?></h3><p><?= e($product['description']) ?></p><div class="product-meta"><span class="price">KSh <?= number_format((float)$product['price']) ?></span><button class="btn btn-outline" data-add-cart="<?= (int)$product['id'] ?>" data-csrf="<?= e(csrf_token()) ?>">Add to cart</button></div></div></article><?php endforeach; ?></div></div></section>
<section class="section"><div class="container story"><div class="story-image"></div><div><div class="eyebrow">A little more than a farm</div><h2>Raised slowly. Shared generously.</h2><p>Golden Eggs began with 40 hens, a borrowed incubator and a simple belief: when birds are cared for well, good food follows. Today, we work with families and small growers across Kiambu to make that care easier to bring home.</p><a class="btn btn-primary" href="about.php">Our farm story →</a><div class="quote"><p>“You can taste the difference in the yolk, but you feel it in the way they show up for you.”</p><strong>— Miriam, founder</strong></div></div></div></section>
<section class="stats"><div class="container section stat-grid"><div class="stat"><strong>12+</strong><span>Years farming</span></div><div class="stat"><strong>4,800</strong><span>Happy customers</span></div><div class="stat"><strong>7 days</strong><span>Freshness promise</span></div><div class="stat"><strong>100%</strong><span>Traceable sourcing</span></div></div></section>
<section class="section"><div class="container"><div class="section-heading"><div><div class="eyebrow">Kind words</div><h2>From our table to yours.</h2></div></div><div class="testimonial-grid"><div class="testimonial"><div class="rating">★★★★★</div><p>“The eggs arrive beautifully packed and the yolks are genuinely golden. We have a standing order now.”</p><strong>— Amina, Lavington</strong></div><div class="testimonial"><div class="rating">★★★★★</div><p>“The chicks were lively and the team gave us a clear starter guide. Such a thoughtful farm.”</p><strong>— Peter, Limuru</strong></div><div class="testimonial"><div class="rating">★★★★★</div><p>“Fast delivery, kind people, and the feed advice saved our little flock.”</p><strong>— Wanjiku, Karen</strong></div></div></div></section>
<section class="section"><div class="container"><div class="section-heading"><div><div class="eyebrow">From the farm journal</div><h2>Notes worth sharing.</h2></div><a class="text-link" href="about.php">Read our story →</a></div><div class="blog-grid"><article class="blog-card"><img src="https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=900&q=85" alt="Fresh eggs in a farm basket" width="900" height="620" loading="lazy"><div class="blog-content"><span class="blog-kicker">Farm basics</span><h3>How to spot a truly fresh egg</h3><p>Simple signs of freshness from shell to yolk, straight from our packing table.</p><a class="text-link" href="about.php">Read note →</a></div></article><article class="blog-card"><img src="https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=900&q=85" alt="Healthy young poultry on the farm" width="900" height="620" loading="lazy"><div class="blog-content"><span class="blog-kicker">Flock care</span><h3>A kinder start for day-old chicks</h3><p>Our first-week checklist for warmth, clean water and confident growth.</p><a class="text-link" href="about.php">Read note →</a></div></article><article class="blog-card"><img src="https://images.unsplash.com/photo-1499529112087-3cb3b73cec95?auto=format&fit=crop&w=900&q=85" alt="Natural poultry feed and grain" width="900" height="620" loading="lazy"><div class="blog-content"><span class="blog-kicker">Good feed</span><h3>What belongs in a healthy flock diet?</h3><p>Choosing balanced feed for layers, broilers and the seasons in between.</p><a class="text-link" href="shop.php?category=Feed">Shop feed →</a></div></article></div></div></section><section class="section recent-section"><div class="container"><div class="section-heading"><div><div class="eyebrow">Back for another look?</div><h2>Recently viewed.</h2></div></div><div class="recent-strip" data-recent-products><div class="empty-state"><p>Products you view will appear here.</p><a class="btn btn-outline" href="shop.php">Browse the farm</a></div></div></div></section><section class="newsletter"><div class="container newsletter-inner"><div><div class="eyebrow">A note from the farm</div><h2>Fresh news, no clutter.</h2><p>Seasonal offers, new arrivals and useful poultry tips.</p></div><form class="newsletter-form" action="newsletter.php" method="post"><input type="email" name="email" placeholder="Your email address" required><button class="btn btn-primary">Subscribe</button></form></div></section>
<?php include 'includes/footer.php'; ?>
