<?php require_once 'config.php'; $pageTitle='Shop the farm'; $category=trim($_GET['category']??''); $search=trim($_GET['q']??''); $products=[]; $categories=[]; try{$categories=db()->query('SELECT * FROM categories ORDER BY name')->fetchAll(); $sql='SELECT p.*, c.name category FROM products p JOIN categories c ON c.id=p.category_id WHERE 1'; $params=[]; if($category){$sql.=' AND c.name=?';$params[]=$category;} if($search){$sql.=' AND (p.name LIKE ? OR p.description LIKE ?)';$params[]="%$search%";$params[]="%$search%";} $sql.=' ORDER BY p.featured DESC,p.created_at DESC';$stmt=db()->prepare($sql);$stmt->execute($params);$products=$stmt->fetchAll();}catch(Throwable $e){} include 'includes/header.php'; ?>
<style>
  .shop-search-shell{position:relative;max-width:100%}
  .shop-search-bar{display:flex;align-items:stretch;background:#fff;border:1px solid var(--line);border-radius:12px;overflow:hidden;min-height:58px;box-shadow:0 3px 12px rgba(32,61,39,.06)}
  .shop-search-bar:focus-within{border-color:var(--green);box-shadow:0 8px 22px rgba(46,125,50,.12)}
  .shop-search-cat{position:relative;display:flex;align-items:center;border-right:1px solid var(--line);background:#f9faf7;min-width:188px}
  .shop-search-cat select{appearance:none;-webkit-appearance:none;background:transparent;border:0;padding:0 36px 0 18px;font:600 .9rem 'DM Sans';color:var(--ink);height:100%;cursor:pointer;min-width:0}
  .shop-search-cat select:focus{outline:0}
  .shop-search-cat i{position:absolute;right:14px;top:50%;transform:translateY(-50%);font-size:.7rem;color:var(--muted);pointer-events:none}
  .shop-search-input-wrap{flex:1;display:flex;align-items:center;padding:0 18px;min-width:0}
  .shop-search-input-wrap input{flex:1;border:0;background:transparent;padding:14px 0;font:500 .92rem 'DM Sans';color:var(--ink);min-width:0}
  .shop-search-input-wrap input:focus{outline:0}
  .shop-search-input-wrap input::placeholder{color:#9aa59c}
  .shop-search-btn{background:var(--green);color:#fff;border:0;padding:0 26px;font:700 .9rem 'DM Sans';cursor:pointer;transition:background .2s ease}
  .shop-search-btn:hover{background:var(--green-dark)}
  @media(max-width:600px){.shop-search-cat{min-width:150px}.shop-search-btn{padding:0 18px}.shop-search-input-wrap{padding:0 12px}}
</style>
<section class="page-hero"><div class="container"><div class="eyebrow">The farm stand</div><h1>Good things,<br>grown close.</h1><p>Fresh eggs, healthy starts and the essentials that make caring for your flock feel simple.</p></div></section>
<section class="section"><div class="container shop-layout"><aside class="filters"><h3>Browse</h3><a class="<?= !$category?'active':'' ?>" href="shop.php">All products</a><?php foreach($categories as $item): ?><a class="<?= $category===$item['name']?'active':'' ?>" href="shop.php?category=<?= urlencode($item['name']) ?>"><?= e($item['name']) ?></a><?php endforeach; ?><hr><p>Every order is packed with care and prepared for local delivery.</p></aside><div><div class="shop-toolbar"><strong><?= count($products) ?> products</strong><form method="get" action="shop.php" class="shop-search-form"><div class="shop-search-shell"><div class="shop-search-bar"><div class="shop-search-cat"><select name="category"><option value="">All Categories</option><?php foreach($categories as $item): ?><option value="<?= e($item['name']) ?>" <?= $category===$item['name']?'selected':'' ?>><?= e($item['name']) ?></option><?php endforeach; ?></select><i class="fa-solid fa-chevron-down"></i></div><div class="shop-search-input-wrap"><input type="text" name="q" value="<?= e($search) ?>" placeholder="Search products e.g. 'day-old chicks'" autocomplete="off"></div><button class="shop-search-btn" type="submit">Search</button></div></div></form></div><div class="product-grid"><?php foreach($products as $product): ?><article class="product-card"><a href="product.php?id=<?= (int)$product['id'] ?>"><div class="product-image <?= str_contains(strtolower($product['category']), 'egg')?'eggs':(str_contains(strtolower($product['category']),'feed')?'feed':'chicks') ?>"><img src="<?= e($product['image'] ?: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=700&q=80') ?>" alt="<?= e($product['name']) ?>" width="700" height="500" loading="lazy"><span class="badge"><?= e(stock_message((int)$product['stock'])) ?></span></div></a><div class="product-info"><div class="rating">★★★★★ <span>(<?= e((string)$product['rating']) ?>)</span></div><h3><?= e($product['name']) ?></h3><p><?= e($product['description']) ?></p><div class="product-meta"><span class="price"><?= money($product['price']) ?></span><?php if($product['stock']>0): ?><button class="btn btn-outline" data-add-cart="<?= (int)$product['id'] ?>" data-csrf="<?= e(csrf_token()) ?>">Add to cart</button><?php else: ?><button class="btn btn-outline" disabled>Currently unavailable</button><?php endif; ?></div></div></article><?php endforeach; ?></div><?php if(!$products): ?><div class="empty-state"><div class="empty-icon">⌕</div><h3>No products found</h3><p>Try another search or browse the full farm collection.</p><a class="btn btn-primary" href="shop.php">View all products</a></div><?php endif; ?></div></div></section>
<?php include 'includes/footer.php'; ?>
