USE golden_eggs;

INSERT IGNORE INTO products (category_id,name,slug,description,price,stock,unit,image,rating,featured) VALUES
((SELECT id FROM categories WHERE slug='fertilized-eggs'),'Improved Kienyeji fertile eggs','improved-kienyeji-fertile-eggs','Strong, carefully selected fertile eggs from our improved Kienyeji breeding flock.','90.00',180,'each','assets/images/chicks.jpg',4.9,1),
((SELECT id FROM categories WHERE slug='fertilized-eggs'),'Rainbow Rooster fertile eggs','rainbow-rooster-fertile-eggs','Hardy fertile eggs selected for colour, vigour and reliable hatching.','110.00',95,'each','assets/images/chicks.jpg',4.8,0),
((SELECT id FROM categories WHERE slug='broilers'),'Broiler day-old chicks','broiler-day-old-chicks','Healthy, fast-growing broiler chicks, vaccinated and ready for your brooder.','115.00',220,'each','assets/images/chicks.jpg',4.9,1),
((SELECT id FROM categories WHERE slug='broilers'),'Broiler grower pack','broiler-grower-pack','A practical starter bundle with broiler chicks and first-stage feeding guidance.','2850.00',20,'pack','assets/images/chicks.jpg',4.7,0),
((SELECT id FROM categories WHERE slug='layers'),'Point-of-lay pullets','point-of-lay-pullets','Healthy young layers selected for dependable production and easy flock management.','1450.00',35,'each','assets/images/chicks.jpg',4.8,1),
((SELECT id FROM categories WHERE slug='layers'),'Layer chick starter pack','layer-chick-starter-pack','A complete starter bundle for raising a productive laying flock.','3600.00',15,'pack','assets/images/chicks.jpg',4.8,0),
((SELECT id FROM categories WHERE slug='feed'),'Layers mash 10kg','layers-mash-10kg','Balanced daily nutrition to support strong shells and consistent laying.','1750.00',30,'10 kg','assets/images/feed.jpg',4.8,1),
((SELECT id FROM categories WHERE slug='feed'),'Broiler finisher 10kg','broiler-finisher-10kg','Energy-rich finisher feed for healthy broiler growth before market age.','1850.00',28,'10 kg','assets/images/feed.jpg',4.7,0),
((SELECT id FROM categories WHERE slug='feed'),'Growers mash 10kg','growers-mash-10kg','Well-balanced nutrition for growing birds between starter and layer stages.','1600.00',32,'10 kg','assets/images/feed.jpg',4.7,0),
((SELECT id FROM categories WHERE slug='feed'),'Calcium supplement 2kg','calcium-supplement-2kg','A mineral supplement for strong shells and healthy laying birds.','650.00',40,'2 kg','assets/images/feed.jpg',4.6,0),
((SELECT id FROM categories WHERE slug='poultry-equipment'),'Automatic drinker','automatic-poultry-drinker','A clean, low-waste drinker for backyard and small commercial flocks.','850.00',24,'each','https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=700&q=80',4.8,1),
((SELECT id FROM categories WHERE slug='poultry-equipment'),'Poultry feeder 5kg','poultry-feeder-5kg','Durable feeder that keeps feed clean and reduces flock waste.','1200.00',18,'each','https://images.unsplash.com/photo-1598894000396-bc30e0a4a7e7?auto=format&fit=crop&w=700&q=80',4.7,0),
((SELECT id FROM categories WHERE slug='poultry-equipment'),'Chick brooder lamp','chick-brooder-lamp','Reliable brooder heat lamp for a warm, comfortable start.','1950.00',14,'each','https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=700&q=80',4.8,0),
((SELECT id FROM categories WHERE slug='poultry-equipment'),'Egg incubator 24 eggs','egg-incubator-24','Compact automatic incubator for reliable small-batch hatching at home.','14500.00',6,'each','https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=700&q=80',4.9,1);