CREATE DATABASE IF NOT EXISTS golden_eggs CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE golden_eggs;

CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(120) NOT NULL, username VARCHAR(50) NOT NULL UNIQUE, email VARCHAR(190) NOT NULL UNIQUE, phone VARCHAR(30), password_hash VARCHAR(255) NOT NULL, role ENUM('customer','admin') NOT NULL DEFAULT 'customer', status ENUM('active','suspended') NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE categories (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE, slug VARCHAR(100) NOT NULL UNIQUE, description TEXT);
CREATE TABLE products (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category_id INT UNSIGNED NOT NULL, name VARCHAR(140) NOT NULL, slug VARCHAR(160) NOT NULL UNIQUE, description TEXT NOT NULL, price DECIMAL(10,2) NOT NULL, stock INT NOT NULL DEFAULT 0, unit VARCHAR(40) NOT NULL DEFAULT 'pack', image VARCHAR(255), rating DECIMAL(2,1) NOT NULL DEFAULT 5.0, featured TINYINT(1) NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT);
CREATE TABLE orders (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, total DECIMAL(10,2) NOT NULL, tax DECIMAL(10,2) NOT NULL DEFAULT 0, shipping DECIMAL(10,2) NOT NULL DEFAULT 0, address TEXT NOT NULL, payment_method ENUM('cod','mpesa','bank') NOT NULL, status ENUM('pending','processing','shipped','delivered','cancelled') NOT NULL DEFAULT 'pending', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE order_items (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id INT UNSIGNED NOT NULL, product_id INT UNSIGNED NOT NULL, quantity INT NOT NULL, unit_price DECIMAL(10,2) NOT NULL, FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE, FOREIGN KEY (product_id) REFERENCES products(id));
CREATE TABLE payments (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id INT UNSIGNED NOT NULL, method VARCHAR(30) NOT NULL, reference VARCHAR(100), status VARCHAR(30) NOT NULL DEFAULT 'pending', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE);
CREATE TABLE cart (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, product_id INT UNSIGNED NOT NULL, quantity INT NOT NULL DEFAULT 1, UNIQUE KEY user_product (user_id, product_id), FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE contacts (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL, subject VARCHAR(180), message TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE newsletter (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(190) NOT NULL UNIQUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE reviews (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, product_id INT UNSIGNED NOT NULL, rating TINYINT NOT NULL, comment TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE admin_activity_log (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, admin_id INT UNSIGNED NOT NULL, action VARCHAR(120) NOT NULL, entity_type VARCHAR(50) NOT NULL, entity_id INT UNSIGNED, details TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE CASCADE);

INSERT INTO categories (name, slug, description) VALUES ('Fresh Eggs','fresh-eggs','Pasture-raised eggs collected daily.'),('Fertilized Eggs','fertilized-eggs','Strong, fertile eggs for your home incubator.'),('Day-old Chicks','day-old-chicks','Healthy, vaccinated chicks for confident starts.'),('Broilers','broilers','Fast-growing broiler breeds.'),('Layers','layers','Reliable laying breeds for small farms.'),('Feed','feed','Balanced nutrition for every growth stage.'),('Poultry Equipment','poultry-equipment','Practical kit for happy, healthy birds.');
INSERT INTO products (category_id,name,slug,description,price,stock,unit,image,rating,featured) VALUES (1,'Sunrise dozen','sunrise-dozen','12 golden-yolk eggs, collected this morning.','420.00',42,'12 eggs','assets/images/eggs.jpg',4.9,1),(1,'Farm crate','farm-crate','30 delicious eggs for busy family kitchens.','980.00',18,'30 eggs','assets/images/eggs.jpg',5.0,1),(2,'Kienyeji fertile eggs','kienyeji-fertile-eggs','Carefully selected fertile eggs, ready for incubation.','75.00',120,'each','assets/images/chicks.jpg',4.8,1),(3,'Kienyeji day-old chicks','kienyeji-day-old-chicks','Vaccinated, lively chicks from our best laying flock.','120.00',250,'each','assets/images/chicks.jpg',4.9,1),(5,'Layers starter pack','layers-starter-pack','A balanced starter bundle for a small laying flock.','3200.00',12,'pack','assets/images/chicks.jpg',4.7,0),(6,'Chick mash 10kg','chick-mash-10kg','Nutrient-dense feed for a strong first month.','1650.00',25,'10 kg','assets/images/feed.jpg',4.8,0);

INSERT IGNORE INTO products (category_id,name,slug,description,price,stock,unit,image,rating,featured) VALUES
((SELECT id FROM categories WHERE slug='fertilized-eggs'),'Improved Kienyeji fertile eggs','improved-kienyeji-fertile-eggs','Strong, carefully selected fertile eggs from our improved Kienyeji breeding flock.','90.00',180,'each','assets/images/chicks.jpg',4.9,1),
((SELECT id FROM categories WHERE slug='fertilized-eggs'),'Rainbow Rooster fertile eggs','rainbow-rooster-fertile-eggs','Hardy fertile eggs selected for colour, vigour and reliable hatching.','110.00',95,'each','assets/images/chicks.jpg',4.8,0),
((SELECT id FROM categories WHERE slug='broilers'),'Broiler day-old chicks','broiler-day-old-chicks','Healthy, fast-growing broiler chicks, vaccinated and ready for your brooder.','115.00',220,'each','assets/images/chicks.jpg',4.9,1),
((SELECT id FROM categories WHERE slug='broilers'),'Broiler grower pack','broiler-grower-pack','A practical starter bundle with broiler chicks and first-stage feeding guidance.','2850.00',20,'pack','assets/images/chicks.jpg',4.7,0),
((SELECT id FROM categories WHERE slug='layers'),'Point-of-lay pullets','point-of-lay-pullets','Healthy young layers selected for dependable production and easy flock management.','1450.00',35,'each','assets/images/chicks.jpg',4.8,1),
((SELECT id FROM categories WHERE slug='layers'),'Layer chick starter pack','layer-chick-starter-pack','A complete starter bundle for raising a productive laying flock.','3600.00',15,'pack','assets/images/chicks.jpg',4.8,0),
((SELECT id FROM categories WHERE slug='feed'),'Layers mash 10kg','layers-mash-10kg','Balanced daily nutrition to support strong shells and consistent laying.','1750.00',30,'10 kg','assets/images/feed.jpg',4.8,1),
((SELECT id FROM categories WHERE slug='feed'),'Broiler finisher 10kg','broiler-finisher-10kg','Energy-rich finisher feed for healthy broiler growth before market age.','1850.00',28,'10 kg','assets/images/feed.jpg',4.7,0),
((SELECT id FROM categories WHERE slug='feed'),'Growers mash 10kg','growers-mash-10kg','Well-balanced nutrition for growing birds between starter and layer stages.','1600.00',32,'10 kg','assets/images/feed.jpg',4.7,0),
((SELECT id FROM categories WHERE slug='feed'),'Calcium supplement 2kg','calcium-supplement-2kg','A mineral supplement for strong shells and healthy laying birds.','650.00',40,'2 kg','assets/images/feed.jpg',4.6,0),
((SELECT id FROM categories WHERE slug='poultry-equipment'),'Automatic drinker','automatic-poultry-drinker','A clean, low-waste drinker for backyard and small commercial flocks.','850.00',24,'each','https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=700&q=80',4.8,1),
((SELECT id FROM categories WHERE slug='poultry-equipment'),'Poultry feeder 5kg','poultry-feeder-5kg','Durable feeder that keeps feed clean and reduces flock waste.','1200.00',18,'each','https://images.unsplash.com/photo-1598894000396-bc30e0a4a7e7?auto=format&fit=crop&w=700&q=80',4.7,0),
((SELECT id FROM categories WHERE slug='poultry-equipment'),'Chick brooder lamp','chick-brooder-lamp','Reliable brooder heat lamp for a warm, comfortable start.','1950.00',14,'each','https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=700&q=80',4.8,0),
((SELECT id FROM categories WHERE slug='poultry-equipment'),'Egg incubator 24 eggs','egg-incubator-24','Compact automatic incubator for reliable small-batch hatching at home.','14500.00',6,'each','https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=700&q=80',4.9,1);
