CREATE DATABASE IF NOT EXISTS golden_eggs CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE golden_eggs;

CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(120) NOT NULL, username VARCHAR(50) NOT NULL UNIQUE, email VARCHAR(190) NOT NULL UNIQUE, phone VARCHAR(30), password_hash VARCHAR(255) NOT NULL, role ENUM('customer','admin') NOT NULL DEFAULT 'customer', status ENUM('active','suspended') NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE categories (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE, slug VARCHAR(100) NOT NULL UNIQUE, description TEXT);
CREATE TABLE products (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category_id INT UNSIGNED NOT NULL, name VARCHAR(140) NOT NULL, slug VARCHAR(160) NOT NULL UNIQUE, description TEXT NOT NULL, price DECIMAL(10,2) NOT NULL, stock INT NOT NULL DEFAULT 0, unit VARCHAR(40) NOT NULL DEFAULT 'pack', image VARCHAR(255), rating DECIMAL(2,1) NOT NULL DEFAULT 5.0, featured TINYINT(1) NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT);
CREATE TABLE orders (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, total DECIMAL(10,2) NOT NULL, tax DECIMAL(10,2) NOT NULL DEFAULT 0, shipping DECIMAL(10,2) NOT NULL DEFAULT 0, address TEXT NOT NULL, payment_method ENUM('cod','mpesa','bank') NOT NULL, status ENUM('pending','processing','shipped','delivered','cancelled') NOT NULL DEFAULT 'pending', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE order_items (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id INT UNSIGNED NOT NULL, product_id INT UNSIGNED NOT NULL, quantity INT NOT NULL, unit_price DECIMAL(10,2) NOT NULL, FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE, FOREIGN KEY (product_id) REFERENCES products(id));
CREATE TABLE payments (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id INT UNSIGNED NOT NULL, method VARCHAR(30) NOT NULL, reference VARCHAR(100), status VARCHAR(30) NOT NULL DEFAULT 'pending', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE);
CREATE TABLE cart (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, product_id INT UNSIGNED NOT NULL, quantity INT NOT NULL DEFAULT 1, UNIQUE KEY user_product (user_id, product_id), FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE contacts (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL, subject VARCHAR(180), message TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE newsletter (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(190) NOT NULL UNIQUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE reviews (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, product_id INT UNSIGNED NOT NULL, rating TINYINT NOT NULL, comment TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE admin_activity_log (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, admin_id INT UNSIGNED NOT NULL, action VARCHAR(120) NOT NULL, entity_type VARCHAR(50) NOT NULL, entity_id INT UNSIGNED, details TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE CASCADE);

INSERT INTO categories (name, slug, description) VALUES ('Fresh Eggs','fresh-eggs','Pasture-raised eggs collected daily.'),('Fertilized Eggs','fertilized-eggs','Strong, fertile eggs for your home incubator.'),('Day-old Chicks','day-old-chicks','Healthy, vaccinated chicks for confident starts.'),('Broilers','broilers','Fast-growing broiler breeds.'),('Layers','layers','Reliable laying breeds for small farms.'),('Feed','feed','Balanced nutrition for every growth stage.'),('Poultry Equipment','poultry-equipment','Practical kit for happy, healthy birds.');
INSERT INTO products (category_id,name,slug,description,price,stock,unit,image,rating,featured) VALUES (1,'Sunrise dozen','sunrise-dozen','12 golden-yolk eggs, collected this morning.','420.00',42,'12 eggs','assets/images/eggs.jpg',4.9,1),(1,'Farm crate','farm-crate','30 delicious eggs for busy family kitchens.','980.00',18,'30 eggs','assets/images/eggs.jpg',5.0,1),(2,'Kienyeji fertile eggs','kienyeji-fertile-eggs','Carefully selected fertile eggs, ready for incubation.','75.00',120,'each','assets/images/chicks.jpg',4.8,1),(3,'Kienyeji day-old chicks','kienyeji-day-old-chicks','Vaccinated, lively chicks from our best laying flock.','120.00',250,'each','assets/images/chicks.jpg',4.9,1),(5,'Layers starter pack','layers-starter-pack','A balanced starter bundle for a small laying flock.','3200.00',12,'pack','assets/images/chicks.jpg',4.7,0),(6,'Chick mash 10kg','chick-mash-10kg','Nutrient-dense feed for a strong first month.','1650.00',25,'10 kg','assets/images/feed.jpg',4.8,0);
