<?php
require_once '../config.php';
if (!current_user() || current_user()['role'] !== 'admin') redirect('../login.php');
$message = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && verify_csrf($_POST['csrf'] ?? null)) {
    $action = $_POST['action'] ?? '';
    $ids = array_values(array_filter(array_map('intval', $_POST['order_ids'] ?? [])));
    if ($action === 'orders_status' && $ids && in_array($_POST['status'] ?? '', ['pending','processing','shipped','delivered','cancelled'], true)) {
        $marks = implode(',', array_fill(0, count($ids), '?'));
        $stmt = db()->prepare("UPDATE orders SET status=? WHERE id IN ($marks)");
        $stmt->execute(array_merge([$_POST['status']], $ids));
        log_admin_activity('Bulk order status update', 'orders', null, $_POST['status'] . ': ' . implode(',', $ids));
        $message = count($ids) . ' orders updated.';
    }
}
$lowStock = db()->query('SELECT id,name,stock FROM products WHERE stock <= ' . LOW_STOCK_THRESHOLD . ' ORDER BY stock ASC')->fetchAll();
$orders = db()->query('SELECT o.id,u.full_name,o.total,o.status,o.created_at FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.created_at DESC LIMIT 50')->fetchAll();
$logs = db()->query('SELECT l.*,u.full_name FROM admin_activity_log l JOIN users u ON u.id=l.admin_id ORDER BY l.created_at DESC LIMIT 20')->fetchAll();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Operations | Admin</title><link rel="stylesheet" href="../assets/css/style.css"></head><body><div class="admin-shell"><aside class="admin-sidebar"><a class="brand" href="index.php"><span class="brand-mark">✦</span><span><strong style="color:#fff">Golden Eggs</strong><small>Admin studio</small></span></a><nav style="margin-top:45px"><a href="index.php">Overview</a><a href="products.php">Products</a><a href="orders.php">Orders</a><a href="customers.php">Customers</a><a href="operations.php">Operations</a><a href="../logout.php">Sign out</a></nav></aside><main class="admin-main"><div class="eyebrow">Admin tools</div><h1>Operations.</h1><?php if($message): ?><div class="notice"><?= e($message) ?></div><?php endif; ?><div class="hero-actions"><a class="btn btn-outline" href="export.php?type=orders">Export orders CSV</a><a class="btn btn-outline" href="export.php?type=customers">Export customers CSV</a></div><section class="section" style="padding:35px 0"><div class="summary"><h3>Low-stock alerts</h3><?php if(!$lowStock): ?><p>All products are above the low-stock threshold.</p><?php else: ?><table class="cart-table"><tbody><?php foreach($lowStock as $item): ?><tr><td><?= e($item['name']) ?></td><td>Only <?= (int)$item['stock'] ?> left</td><td><a class="text-link" href="products.php">Manage →</a></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></div></section><section><div class="summary"><h3>Bulk order actions</h3><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="orders_status"><select class="form-control" name="status" style="max-width:220px;margin-bottom:15px"><option value="processing">Processing</option><option value="shipped">Shipped</option><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option></select><table class="cart-table"><thead><tr><th></th><th>Order</th><th>Customer</th><th>Status</th></tr></thead><tbody><?php foreach($orders as $order): ?><tr><td><input type="checkbox" name="order_ids[]" value="<?= (int)$order['id'] ?>"></td><td>#<?= (int)$order['id'] ?></td><td><?= e($order['full_name']) ?></td><td><?= e(ucfirst($order['status'])) ?></td></tr><?php endforeach; ?></tbody></table><button class="btn btn-primary" style="margin-top:15px">Update selected orders</button></form></div></section><section class="section" style="padding:35px 0"><div class="summary"><h3>Recent activity</h3><?php foreach($logs as $log): ?><div class="summary-line"><span><?= e($log['full_name']) ?> · <?= e($log['action']) ?></span><small><?= e($log['created_at']) ?></small></div><?php endforeach; ?></div></section></main></div></body></html>
